version: 0.0
os: linux
file:
  - source: /
    destination: /home/ec2-user/calorie-counter
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ec2-user